### ISSUE TITLE
Needs better token management.

### ISSUE THREAD

**Issue by MasonSchneider** [claudiowilson/FogbugzJS#3]
It's unspecified how tokens are handled. Need to either make the token global so the user doesn't worry about it or make the CallAPI function insert this automatically.

**Comment by claudiowilson** [comment]
SHA: 58030ad1918756ba529c53c7ed38a55789aca9aa fixes this!

**Comment by claudiowilson** [comment]
I accidentally committed a comment though, I'll remove that in future commits :/
