### ISSUE TITLE
Having trouble getting tests to run.

### ISSUE THREAD

**Issue by MasonSchneider** [claudiowilson/FogbugzJS#4]
Can you tell me what extras you have installed? I have node running but when I do node test.js with my info in settings I get an error for not finding express.

**Comment by claudiowilson** [comment]
Have you ran `npm install` on your directory? Maybe you haven't installed express. All I have are `coffee-script, express, and xml2js` Also, update to the latest head. There were a lot of bug fixes I had to add.

**Comment by MasonSchneider** [comment]
I got it running, now I get this when trying to log in, any clue why?

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

**Comment by claudiowilson** [comment]
You probably don't have the correct URL for the site. In `settings.js` the format should be `module.exports.apiURL = 'https://<sitename>.fogbugz.com/api.asp?';` We might want to edit that so that the user only has to put the first part and we could just append the `/api.asp?` part

**Comment by MasonSchneider** [comment]
That fixed it. I changed the set URL to actually append this and add https:// so the only thing that needs to be in settings now is the actual URL.
